FROM python:3.9
WORKDIR /app

COPY /requirements.txt /server/ /.flaskenv /electron_visualized.py ./
RUN apt-get update && apt-get install -y python3-dev gfortran libopenblas-dev libxc-dev libscalapack-mpi-dev libfftw3-dev
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:electron_visualized"]