FROM python:3.9
WORKDIR /app

COPY /requirements.txt /server/ /.flaskenv ./
RUN apt-get update && apt-get install -y build-essential && apt-get install -y binutils && apt-get install -y python3-dev && apt-get install -y gfortran && apt-get install -y liblapack-dev && apt-get install -y libopenblas-dev && apt-get install -y libxc-dev && apt-get install -y libscalapack-mpi-dev && apt-get install -y libfftw3-dev
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:electron_visualized"]