# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY /client/package.json yarn.lock ./
COPY /client/src ./src
COPY /client/public ./public
RUN yarn install
RUN yarn build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY client/public/nginx.default.conf /etc/nginx/conf.d/default.conf