/*
CONSTANTS FOR ELECTRONVISUALIZED — DEVELOPED AND DESIGNED BY JOHN SEONG
*/

const CANVAS = {
    WIDTH: "100vw",
    HEIGHT: "85vh"
};

export const RENDERER = {
    ATOM_RADIUS: "0.3",
    TUBE_RADIUS: "0.3"
}

export default CANVAS;